---

- name: "03.1 - place all the pki data into appropriate place"
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default('ug=rwX,o-rwx') }}"
  become: yes
  loop_control:
    label: "{{ item.dest }}"
  loop:
    - content: "{{ k8s_worker_kubernetes_ca_cert }}"
      dest: "{{ __k8s_worker_kubernetes_ca_cert_file }}"
    - content: "{{ k8s_worker_kubelet_cert }}"
      dest: "{{ __k8s_worker_kubelet_cert_file }}"
    - content: "{{ k8s_worker_kubelet_key }}"
      dest: "{{ __k8s_worker_kubelet_key_file }}"
      mode: "u=rwX,go-rwx"
    - content: "{{ k8s_worker_kube_proxy_cert }}"
      dest: "{{ __k8s_worker_kube_proxy_cert_file }}"
    - content: "{{ k8s_worker_kube_proxy_key }}"
      dest: "{{ __k8s_worker_kube_proxy_key_file }}"
      mode: "u=rwX,go-rwx"
