#jinja2: lstrip_blocks: True, trim_blocks: True
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clientConnection:
  kubeconfig: "{{ __k8s_worker_kube_proxy_kubeconfig_file }}"
mode: "iptables"
clusterCIDR: "{{ k8s_worker_kubernetes_cluster_pod_cidr }}"
